[package]
name = "codefixer_srv"
version = "0.1.0"
edition = "2024"
default-run = "codefixer_srv"

[dependencies]
codefixer_shared_interface.workspace = true
anyhow.workspace = true
askama.workspace = true
axum.workspace = true
axum-anyhow.workspace = true
derive_more.workspace = true
dotenv.workspace = true
futures.workspace = true
futures-util.workspace = true
jsonwebtoken.workspace = true
oauth2.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tower-sessions.workspace = true
tower-sessions-sqlx-store.workspace = true
axum-login.workspace = true
url.workspace = true
tower.workspace = true
axum-extra.workspace = true
sea-query.workspace = true
tower-http.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
regex.workspace = true

[[bin]]
name = "gen-openapi"
path = "./src/gen_openapi.rs"
