[package]
name = "codefixer_functions"
version = "0.1.0"
edition = "2024"

[dependencies]
codefixer_shared_interface.workspace = true
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
derive_more.workspace = true
lambda_runtime = { version = "1.3.0", features = ["anyhow", "concurrency-tokio" ] }

[[bin]]
name = "compile_submission"
path = "src/compile_submission.rs"
